# Form implementation generated from reading ui file 'NewPreference_form.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 463)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(170, 20, 221, 31))
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 150, 511, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.daytime = QtWidgets.QLabel(self.layoutWidget)
        self.daytime.setObjectName("daytime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.daytime)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.monday = QtWidgets.QCheckBox(self.layoutWidget)
        self.monday.setObjectName("monday")
        # when monday is selected
        self.monday.toggled.connect(self.item_selected)
        self.horizontalLayout.addWidget(self.monday)
        self.timeEditMonStart = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditMonStart.setObjectName("timeEditMonStart")
        self.horizontalLayout.addWidget(self.timeEditMonStart)
        self.timeEditMonEnd = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditMonEnd.setObjectName("timeEditMonEnd")
        self.horizontalLayout.addWidget(self.timeEditMonEnd)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tuesday = QtWidgets.QCheckBox(self.layoutWidget)
        self.tuesday.setObjectName("tuesday")
        # when tuesday is selected
        self.tuesday.toggled.connect(self.item_selected)
        self.horizontalLayout_2.addWidget(self.tuesday)
        self.timeEditTuesStart = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditTuesStart.setObjectName("timeEditTuesStart")
        self.horizontalLayout_2.addWidget(self.timeEditTuesStart)
        self.timeEditTuesEnd = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditTuesEnd.setObjectName("timeEditTuesEnd")
        self.horizontalLayout_2.addWidget(self.timeEditTuesEnd)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wednesday = QtWidgets.QCheckBox(self.layoutWidget)
        self.wednesday.setObjectName("wednesday")
        # when wednesday is selected
        self.wednesday.toggled.connect(self.item_selected)
        self.horizontalLayout_3.addWidget(self.wednesday)
        self.timeEditWedStart = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditWedStart.setObjectName("timeEditWedStart")
        self.horizontalLayout_3.addWidget(self.timeEditWedStart)
        self.timeEditWedEnd = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditWedEnd.setObjectName("timeEditWedEnd")
        self.horizontalLayout_3.addWidget(self.timeEditWedEnd)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.thursday = QtWidgets.QCheckBox(self.layoutWidget)
        self.thursday.setObjectName("thursday")
        # when thursday is selected
        self.thursday.toggled.connect(self.item_selected)
        self.horizontalLayout_5.addWidget(self.thursday)
        self.timeEditThurStart = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditThurStart.setObjectName("timeEditThurStart")
        self.horizontalLayout_5.addWidget(self.timeEditThurStart)
        self.timeEditThurEnd = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditThurEnd.setObjectName("timeEditThurEnd")
        self.horizontalLayout_5.addWidget(self.timeEditThurEnd)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Friday = QtWidgets.QCheckBox(self.layoutWidget)
        self.Friday.setObjectName("Friday")
        # when friday is selected
        self.Friday.toggled.connect(self.item_selected)
        self.horizontalLayout_4.addWidget(self.Friday)
        self.timeEditFriStart = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditFriStart.setObjectName("timeEditFriStart")
        self.horizontalLayout_4.addWidget(self.timeEditFriStart)
        self.timeEditFriEnd = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEditFriEnd.setObjectName("timeEditFriEnd")
        self.horizontalLayout_4.addWidget(self.timeEditFriEnd)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_6)
        self.kursus = QtWidgets.QLabel(Form)
        self.kursus.setGeometry(QtCore.QRect(10, 90, 141, 21))
        self.kursus.setObjectName("kursus")
        self.pushButtonOk = QtWidgets.QPushButton(Form)
        self.pushButtonOk.setGeometry(QtCore.QRect(370, 430, 75, 24))
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.pushButtonCancel = QtWidgets.QPushButton(Form)
        self.pushButtonCancel.setGeometry(QtCore.QRect(450, 430, 75, 24))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.pushButtonClear = QtWidgets.QPushButton(Form)
        self.pushButtonClear.setGeometry(QtCore.QRect(10, 420, 75, 24))
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(130, 90, 391, 31))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def item_selected(self, item):
        value = ""

        if self.monday.isChecked():
            value = self.monday.text()

        if self.tuesday.isChecked():
            value = self.tuesday.text()

        if self.wednesday.isChecked():
            value = self.wednesday.text()

        if self.thursday.isChecked():
            value = self.thursday.text()

        if self.Friday.isChecked():
            value = self.Friday.text()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#aa0000;\">Indstil Præferencer</span></p></body></html>"))
        self.daytime.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">Ugedage og tidsrum</span></p></body></html>"))
        self.monday.setText(_translate("Form", "Mandag"))
        self.tuesday.setText(_translate("Form", "Tirsdag"))
        self.wednesday.setText(_translate("Form", "Onsdag"))
        self.thursday.setText(_translate("Form", "Torsdag"))
        self.Friday.setText(_translate("Form", "Fredag"))
        self.kursus.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">Kursus Valgt</span></p></body></html>"))
        self.pushButtonOk.setText(_translate("Form", "Anmod"))
        self.pushButtonCancel.setText(_translate("Form", "Anuller"))
        self.pushButtonClear.setText(_translate("Form", "Nulstil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
