from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class NewUser(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 272)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UniID = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.UniID.setFont(font)
        self.UniID.setObjectName("UniID")
        self.horizontalLayout.addWidget(self.UniID)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Password = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Password.setFont(font)
        self.Password.setObjectName("Password")
        self.horizontalLayout_2.addWidget(self.Password)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(Form)

        # Connect to database and execute the query with desired values when the pushbutton is pressed.
        self.pushButton.clicked.connect(self.save_user)

        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def save_user(self):
        try:
            mydb = mc.connect(
                host="127.0.0.1",
                user="root",
                password="Pattefar3638",
                database="mydb"
            )
            cursor = mydb.cursor()
            # We save the inserted text from the GUI lineedit into variables
            # In the real world uniID is properly autogenerated.
            uniID = self.lineEdit.text()
            password = self.lineEdit_2.text()

            # Insert into the 'bruger' database in uniID and password fields.
            # Using a sring placeholder, we can insert values from python variables
            query = "INSERT INTO bruger (UniID, Password) VALUES (%s, %s)"
            value = (uniID, password)

            # Now we have to execute the query we made
            cursor.execute(query, value)
            mydb.commit()

            # If all this is going well, we want the result to be visible in the Gui
            self.result.setText("Du har nu succesfuldt oprettet en bruger")

        # If all this is going wrong, we want the result to be visible in the Gui
        except mc.Error as e:
            self.result.setText("Oprettelse af bruger mislykkedes")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.UniID.setText(_translate("Form", "UniID:"))
        self.Password.setText(_translate("Form", "Password:"))
        self.pushButton.setText(_translate("Form", "Opret Bruger"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = NewUser()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
